version: '3.7'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    hostname: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/influxdb-storage:/var/lib/influxdb
    env_file:
      - ./influxdb/.env.influxdb
    networks:
      - backend

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - ./postgres/.env.postgres
    volumes:
      - ./postgres/postgres-storage:/var/lib/postgresql
      - ./postgres/init-sql/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./postgres/init-sql/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./pgadmin/.env.pgadmin
    volumes:
      - ./pgadmin/pgadmin-storage:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    depends_on:
      - postgres
    restart: unless-stopped

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    network_mode: host
    depends_on:
      - influxdb
      - postgres
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./nginx/log:/var/log/nginx

  grafana:
    image: grafana/grafana:7.2.1
    container_name: grafana
    depends_on:
      - telegraf
    env_file:
      - ./grafana/.env.grafana
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - ./grafana/grafana-storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - frontend
      - backend

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html/:/etc/nginx/html/
      - ./nginx/log:/var/log/nginx
    networks:
      - monitoring
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - grafana
networks:
  frontend:
  monitoring:
  backend:
