CREATE TABLE COMPANY(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   ADDRESS        CHAR(50)
);

CREATE TABLE EMPLOYEE(
   ID INT PRIMARY KEY     NOT NULL,
   FIRST_NAME           TEXT    NOT NULL,
   LAST_NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         REAL,
   COMPANY_ID INT,
   CONSTRAINT FK_COMPANY
      FOREIGN KEY(COMPANY_ID)
	  REFERENCES COMPANY(ID)
);
